
import math
from PySide6.QtWidgets import QApplication
from PySide6.QtUiTools import QUiLoader

def number () : ...
def point () : ...
def minus () : ...
def sum () : ...
def sub () : ...
def multi () : ...
def divide () : ...
def sqrt () : ...
def percent () : ...
def log () : ...
def sin () : ...
def cos () : ...
def tan () : ...
def cot () : ...
def ac () : ...
def equal () : ...

app = QApplication ([])
loader = QUiLoader ()
window = loader.load ("calculator\calculator.ui")
window.show ()
app.exec ()

